name = "kucho-store-app"
pages_build_output_dir = "./dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "kucho-store-db"
database_id = "882f097a-6ae9-404e-adf0-b8313548d1e1"

[vars]
JWT_SECRET = "x8wks81zZksKOaxk8291"
